INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project1", "category1", 1, "1/1/01", "1/1/11");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project2", "category2", 2, "1/2/01", "1/1/12");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project3", "category3", 3, "1/3/01", "1/1/13");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project4", "category4", 4, "1/4/01", "1/1/14");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project5", "category5", 5, "1/5/01", "1/1/15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project6", "category6", 6, "1/6/01", "1/1/16");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project7", "category7", 7, "1/7/01", "1/1/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project8", "category8", 8, "1/8/01", "1/1/18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project9", "category9", 9, "1/9/01", "1/1/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project10", "category10", 10, "1/10/01", "1/1/20");

INSERT INTO users (name, age) VALUES ("1", 26);
INSERT INTO users (name, age) VALUES ("2", 26);
INSERT INTO users (name, age) VALUES ("3", 26);
INSERT INTO users (name, age) VALUES ("4", 26);
INSERT INTO users (name, age) VALUES ("5", 26);
INSERT INTO users (name, age) VALUES ("6", 26);
INSERT INTO users (name, age) VALUES ("7", 26);
INSERT INTO users (name, age) VALUES ("8", 26);
INSERT INTO users (name, age) VALUES ("9", 26);
INSERT INTO users (name, age) VALUES ("10", 26);
INSERT INTO users (name, age) VALUES ("11", 26);
INSERT INTO users (name, age) VALUES ("12", 26);
INSERT INTO users (name, age) VALUES ("13", 26);
INSERT INTO users (name, age) VALUES ("14", 26);
INSERT INTO users (name, age) VALUES ("15", 26);
INSERT INTO users (name, age) VALUES ("16", 26);
INSERT INTO users (name, age) VALUES ("17", 26);
INSERT INTO users (name, age) VALUES ("18", 26);
INSERT INTO users (name, age) VALUES ("19", 26);
INSERT INTO users (name, age) VALUES ("20", 26);

INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
